projects:
  EvalPlugin:
    path: EvalPlugin
  DailyReward:
    path: DailyReward
  SessionsExample:
    path: SessionsExample
  SimplePermissions:
    path: SimplePermissions
  JoinDisplays:
    path: JoinDisplays
  ConfigSalad:
    path: ConfigSalad
  MentionPings:
    path: MentionPings
