# https://poggit.pmmp.io/ci/SOF3/simple-plugins
projects:
  EvalPlugin:
    path: EvalPlugin
  DailyReward:
    path: DailyReward
  SessionsExample:
    path: SessionsExample
  SimplePermissions:
    path: SimplePermissions
  JoinDisplays:
    path: JoinDisplays
  ConfigSalad:
    path: ConfigSalad
  MentionPings:
    path: MentionPings
  ConsolePush:
    path: ConsolePush
  DelayedForms:
    path: DelayedForms
  LessIsMore:
    path: LessIsMore
  DeadlyFlight:
    path: DeadlyFlight
