name: LessIsMore
version: 1.0.0
api:
- 3.0.0-ALPHA11 # uses TextFormat::colorize()
- 3.0.0-ALPHA12
author: SOFe
main: SOFe\LessIsMore\LessIsMore

permissions:
  lessismore:
    description: Root permission node for commands created with LessIsMore
